apiVersion: v1
kind: Pod
metadata:
  name: simple-pod  # name of the pod
  namespace: roboshop # attach to the namespace, if you dont specify namespace then it will attach to default namespace
spec:
  containers:
  - name: nginx-simple
    image: nginx:1.14.2
    ports: 
    - containerPort: 80

